### ISSUE TITLE
Question: Issue with Random Additions and bdew.lib?

### ISSUE THREAD

**Issue by jermangarc** [bdew-minecraft/bdlib#11]
I'm having an issue with Random Additions not rendering blocks and having massive drops in FPS. In the console there are hundreds of spamming messages http://pastebin.com/hJ6pCVgd. 

I've submitted an issue report to @CreativeMD at https://github.com/CreativeMD/RandomAdditions/issues/7, but I thought I'd let you know, maybe you can shed some light on the matter? Thanks.

**Comment by bdew** [comment]
He's doing something stupid, i'll give the details in his issue but for now change RenderingModelID in his config to something different
