### ISSUE TITLE
bdlib isnt working at all

### ISSUE THREAD

**Issue by armywolf08** [bdew-minecraft/bdlib#12]
IT conflicts with every api I have installed on the modpack. It is a custom modpack with over 200 mods and very much stable with just this little hickup with gendustry and tesseracts directly touching eachother.

here is my crash log.
http://pastebin.com/acjKbKHg

**Comment by bdew** [comment]
It doesn't conflict with anything and has nothing to do with your crash

Your pressure pipes versions is very out of date - http://bdew.net/pressure/ 

Try updating it first and if you are still having problems paste the new crash

**Comment by bdew** [comment]
Due to no response I'm assuming that this is fixed and closing the issue. If the problem still exists please comment here or open a new issue.
