### ISSUE TITLE
minimum version needed 1.7.2.76

### ISSUE THREAD

**Issue by EldraziCat** [bdew-minecraft/bdlib#15]
every time i boot up the game it says the minimum version of bdlib i need is 1.7.2.76 and that version isn't even released yet is it?

**Comment by bdew** [comment]
It's a dev version, available from [jenkins](http://jenkins.bdew.net/job/bdlib-1.7.10/)

If you are using jenkins builds of any of my other mods (Gendustry, Pressure Pipes, Advanced Generators, AE2 Stuff) - you will generally need to grab everything else from jenkins as well, including BDlib.

**Comment by bdew** [comment]
Scratch that... The versions of AE2Stuff i put on CurseForge is built against the wrong version of BDLib. I'll put an update ASAP.

**Comment by bdew** [comment]
If you had this error because of updating AE2 Stuff - [update it to 0.2.1](http://minecraft.curseforge.com/mc-mods/225194-ae2-stuff/files/2236796).
