### ISSUE TITLE
Crash on Startup BD Lib 1.9.0.94

### ISSUE THREAD

**Issue by spidey1958** [bdew-minecraft/bdlib#17]
When I load BD Lib 1.9.0.94 I get the following error on starting minecraft I do not get the issue when udsing version 1.8.2.92. I'm using Forge 10.13.4.1448.

http://pastebin.com/DZCK2PnQ

**Comment by spidey1958** [comment]
Same error if I use Pressure Pipes 1.2.0.101 or 1.2.1.108

**Comment by bdew** [comment]
Pressure pipes 1.2.1.108 should work with bdlib 1.9.0, if it doesn't please post the log from that.

**Comment by McyD** [comment]
Just tried to update same issue when using Gendustry.  No pressure pipes installed.

http://pastebin.com/2inr1twv

**Comment by bdew** [comment]
> Just tried to update same issue when using Gendustry. No pressure pipes installed.

You have old advanced generators. Update to 0.9.14 release

**Comment by McyD** [comment]
Should have noticed the reference to generators.  TY.

**Comment by spidey1958** [comment]
Made sure that Gendustry, Advanced Generators and Pressure Pipes on current version and seem to resolve the issue.(Sorry could of sworn I was on latest Generators)
