### ISSUE TITLE
Can't figure out why it's crashing :(

### ISSUE THREAD

**Issue by Phantum** [bdew-minecraft/bdlib#18]
http://pastebin.com/9CBqkQMS

trying to update bdlib so that I can use the tiered turbines.  Not sure what I did wrong, and trying to update to forge 1.7.2 breaks everything :/

**Comment by bdew** [comment]
You have a mishmash of incompatible old versions.

The current release of Advanced Generators is 0.9.17
It's intended for use with BDLib 1.9.1

You can download both from http://bdew.net/generators/

I have no idea what "forge 1.7.2" is. The current recommended version of forge for Minecraft 1.7.10 is 10.13.4.1448. If you mean minecraft 1.7.2 it's not supported by any modern mods.
