### ISSUE TITLE
Upgrade Bdlib from 1.8.2.92 too 1.9.2.104  and it crashes my server.

### ISSUE THREAD

**Issue by Daphonic** [bdew-minecraft/bdlib#20]
https://www.dropbox.com/s/5h4wkofi5cr7x16/fml-server-latest.log?dl=0

thats latest log.

any help would be appreciated.

**Comment by bdew** [comment]
Update all my mods that you have to the latest stable version - https://bdew.net/2015/09/10/updates-gendustry-advanced-generators-pressure-pipes-ae2-stuff/

There are some backwards incompatible changes in BDLib that will not work with older versions of the other mods.
