### ISSUE TITLE
[Suggestion] Move all config parsers and crafting handlers to core mod.

### ISSUE THREAD

**Issue by OneEyeMaker** [bdew-minecraft/bdlib#21]
Hello, @bdew !
Firstly. great thanks for your mods!
Secondly, I have a simle suggestion (that can be realized not so simply). Please, move to BDLib all crafting handlers, that you use to apply recipes from config files. 
For example, now I can add recipe for Assembly Table only in configs of GenDustry. But I can't do that in configs of AdvancedGenerators (It's logical to use some kind of advanced crafting table to make advanced generator, isn't it?).
And I suggest to move all handlers/config parsers (for shaped/shapeless crafting, smelting, TE/EIO smelting and alloying, crafting in assembly table, Centrifuge, Squeezer, etc.) to BDLib; it'll be conveniently to use its with all mods, that support BACON.

P. S. And sorry for my English, I'm from Russia.

**Comment by bdew** [comment]
I don't want to have build-time dependencies on other mods in bdlib. As of now big version transitions between dependencies are already a pain in the rear to keep everything smooth and having additional dependencies in bdlib would make that even more painful.
