### ISSUE TITLE
Error while processing RsAssembly

### ISSUE THREAD

**Issue by Tsyklop** [bdew-minecraft/bdlib#22]
Error in the log file: http://pastebin.com/2dGixGaG

bdlib-1.9.3.107-mc1.7.10
gendustry-1.6.3.128-mc1.7.10

**Comment by bdew** [comment]
Looks like you have the same assembly recipe ID registered twice? Do you have any custom configs that add assembly recipes?

**Comment by Tsyklop** [comment]
Yes.It looks like it. I copied the recipe files from jar file gendustry.

**Comment by Tsyklop** [comment]
Yes. My bad. Sorry.
