### ISSUE TITLE
1.9-1.11.0.10 crashes dedicated forge server 1.9 build 1821 on startup

### ISSUE THREAD

**Issue by kreezxil** [bdew-minecraft/bdlib#25]
Issue: bdlib-1.9-1.11.0.10 crashes dedicated forge server 1.9 build 1821 on startup

crash report:
https://gist.github.com/9dc348c0ac889ffb5e579d3632305f3c

fml server latest:
https://gist.github.com/058e74502370f653808e0c676645d7b2

**Comment by bdew** [comment]
MinecraftForge/MinecraftForge@6e04a6c572a6a0d14b21c62f19d6a5a9389a9def broke something.

Try this build: http://minecraft.curseforge.com/projects/bdlib/files/2291723
