### ISSUE TITLE
NPE when running dumpregistry

### ISSUE THREAD

**Issue by F4ndroid** [bdew-minecraft/bdlib#26]
http://pastebin.com/fmQ7DEZn

MC version: 1.10.2
bdlib: 1.12.1.4

**Comment by bdew** [comment]
That crash doesn't make sense to me. I guess it's some other mod doing something weird with how their blocks are registered.

What other mods are you using?

**Comment by bdew** [comment]
Please try this build: http://minecraft.curseforge.com/projects/bdlib/files/2317576

It should produce a warning that will show what the offending block is and what mod it comes form.

**Comment by F4ndroid** [comment]
It didn't produce any warning but it did successfully produce the registry dump. Did you want to see it?

**Comment by bdew** [comment]
The dump isn't really useful. If it didn't produce any warnings it means that whatever was broken isn't broken anymore *shrug*.

I'm closing this, if you get any warnings or another NPE in the future - comment here and i'll reopen it.
