### ISSUE TITLE
V 1.12.2.8 looking for scala things that don't exist on servers?

### ISSUE THREAD

**Issue by Claycorp** [bdew-minecraft/bdlib#27]
http://pastebin.com/EPJTLvTU

This was a fresh install of forge 2044 server.

**Comment by bdew** [comment]
Your install is borked. 

You should have libraries\org\scala-lang\scala-library\2.11.1\scala-library-2.11.1.jar in your server folder (this is installed by forge installer). If that is missing or not loaded for some reason - you will get an error like that.

If you used the official forge installer - try redownloading/reinstalling. If you use some other launcher or installer - report the error to it's authors.

**Comment by Claycorp** [comment]
Yeap. Thanks for the quick reply. Must have had an internet derp that messed up my install.
