### ISSUE TITLE
1.10.2 /oredistribution doesnt see Ic2 ores

### ISSUE THREAD

**Issue by MrNinja93** [bdew-minecraft/bdlib#28]
Oredistribution command doesn't seem to be picking up ic2 ores, private modpack unified ores to Ic2 disabling forestry copper leads to copper not being generated in the distribution list same for tin/lead. 

If I swap oregen to forestry/immersive engineering the command sees them so seems to only affect Ic2.

Version: bdlib-1.12.2.10-mc1.10.2

Edit Screenshot
Edit 2 Uranium from immersive engineering is enabled as well as ic2 which is why that's showing up

![2016-09-07_22 16 39](https://cloud.githubusercontent.com/assets/21979276/18328864/da7063ec-7548-11e6-949d-27b6f4dc387f.png)

**Comment by bdew** [comment]
Looks like IC2 doesn't support the method i was using to get the metadata. Changed it to a slightly different method... hopefully won't break with some other mod.
