### ISSUE TITLE
major refactor of WidgetContainer chain ..

### ISSUE THREAD

**Issue by piotrb** [bdew-minecraft/bdlib#3]
I'm trying to extend it and its being a huge pain ..

I want to add a new method to it, a second variant of draw, right now draw is meant for drawing the "active" part of the widget, I want to have 2 parts to a widget, the passive and the active one. The passive is drawn along with the window background from drawGuiContainerBackgroundLayer

I plan to extend all your widgets, but if you're willing I'd rather just pull request a refactor and integrate this background layer rendering right at its core.

**Comment by piotrb** [comment]
How do you work easily with bdlib in local dev? Right now I just pull it from your maven ...

**Comment by bdew** [comment]
Does that help - 26137a88d7aef5d0b40436592b7173081355c178?

For dev environment i just manually remove it as a library and add as a source folder in IDEA module settings when i want to work on it.

**Comment by piotrb** [comment]
That looks like a great start, I'll get back to you how well that integrates .. build 30 here I go ;)

**Comment by piotrb** [comment]
Close ... only one bit missing .. the background rendering needs to be wrapped in a translate, otherwise it is not oriented into the gui itself .. had to hack that into my initial attempt .. 

Simple enough:

``` scala
GL11.glPushMatrix
GL11.glTranslatef(this.guiLeft.toFloat, this.guiTop.toFloat, 0.0F)
// render the stuff
GL11.glPopMatrix
```

You do seem to have something simillar, but it doesn't seem to have any effect .. 

Not sure if its my use of subcontainers in the inventory grid or what .. maybe have a quick look at my code .. 

https://github.com/piotrb/hamcraft/commit/9c5876393f930579cb46d5f899c03dd07819b9be

**Comment by bdew** [comment]
The issue was that for drawGuiContainerForegroundLayer() this translation was done by vanilla code but drawGuiContainerBackgroundLayer() happens before that so i had to add it manually. Should work now

**Comment by piotrb** [comment]
Thanks, all fixed
