### ISSUE TITLE
Feature Request for BACON - Mass Blacklisting

### ISSUE THREAD

**Issue by 666lumberjack** [bdew-minecraft/bdlib#30]
Apologies if this isn't on the right issue tracker, but I'm trying to tweaks some things using BACON and there doesn't seem to be a good way to do it without writing hundreds of lines of code. Specifically, I want to blacklist all the default sources of carbon/mutagen in Advanced Generators and Gendustry so that I can make a couple of specific items the only way to get them. 

However, there doesn't seem to be a way to do this without manually adding every item to the blacklist (or setting the mutagen value for it to 0) which is quite tedious, especially for carbon as there are hundreds of valid sources. Am I just unaware of the correct syntax to do this?

**Comment by bdew** [comment]
Hm, i'll add something for that. For now you can use the override folder to completely override a config file and load it instead of the one in the jar.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
