### ISSUE TITLE
Updating my game to latest version of Gendustry and BdLib crashed my game

### ISSUE THREAD

**Issue by Garonne** [bdew-minecraft/bdlib#31]
Got a crash seemingly related to BdLib after I updated Gendustry and BdLib to latest versions.

You might want to check it.

[2016-11-12-3.log.gz](https://github.com/bdew/bdlib/files/587180/2016-11-12-3.log.gz)

**Comment by bdew** [comment]
I think something went wonky with your update

> [12:39:53] [Client thread/ERROR]: The mod gendustry (GenDustry) requires mod versions [bdlib@[1.12.2.12,)] to be available

Check that all the right files are where they should be, or maybe something got corrupted in downloading.

**Comment by Garonne** [comment]
Ok, bdlib and gendustry do seem to run after redownloading both files... Sadly "Advanced Generators" doesn't like to play with me anymore 0.9.20.4 and 0.9.20.18 both crashing. Want me to post those here or switch over to github for "Advanced Generators" and post crashlogs there?

**Comment by bdew** [comment]
if it's still happening - open a new issue there.
