### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by chazwarp923** [bdew-minecraft/bdlib#35]
Since I'm not sure whether this is Pressure Pipes or BD Lib ill just put this here.
http://pastebin.com/ddYsdD8G
I get this crash rather frequently, but at random times, i never know when it might happen.
Sometimes it doesn't happen for hours, sometimes it happens within minutes of startup. I really have no clue.
Forge: 2185
BD Lib: 1.12.2.20
Pressure Pipes: 1.3.1.22

Server log: https://www.dropbox.com/s/pnixx0e3kgcokfs/fml-server-latest.log?dl=1

**Comment by bdew** [comment]
That error makes no sense to me.

> java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=signal, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{**block=minecraft:stone**, properties=[variant]}

It complains about the block not having the right property, and says that the block is stone, but....

> Block type: ID #1576 (tile.pressure.input // net.bdew.pressure.blocks.input.BlockInput$)

The block is not stone, and should have that property...

>  Block location: World: (7,61,155)

Can you check what's actually going on in this location?

**Comment by chazwarp923** [comment]
![2017-01-12_02 54 31](https://cloud.githubusercontent.com/assets/1704521/21881490/90ff87f0-d872-11e6-9e34-adf4e25231bf.png) That is a picture of the setup in question, i don't see anything wrong.

**Comment by bdew** [comment]
Hm neither do i, this is weird.

Any suspicion on what might be triggering the crash or it just happens out of the blue?

This setup is really redundant by the way, you could just use a pump or an input(with RS signal)+output to do the same thing, no need for all three :P

**Comment by chazwarp923** [comment]
It just happens randomly for no reason, like I said, sometimes it happens a couple minutes in, other times it just never happens. I tried breaking and replacing all the blocks so I guess we'll see if that fixes it. And P.S. I didn't know I could do that :P

**Comment by chazwarp923** [comment]
Just got the crash again, even after breaking and replacing the blocks.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
