### ISSUE TITLE
BDLib Starting error on windows 10

### ISSUE THREAD

**Issue by OscarAblinger** [bdew-minecraft/bdlib#37]
Strangly BDLib and with it all its dependencies crash, when I start them with minecraft on my Laptop (windows 10), but not on my PC (Windows 7) with the same settings.
I regularly update my Java version on both computers and I have also already tried different minecraft settings, but I'm not quite sure what causes the problem. (Especially since there isn't already another issue, although that crash is happening to me since 1.7)

Crash Report: (with only BDLib installed): http://pastebin.com/auNDL77D
It seems it doesn't like the Java I use, but I have already tried reinstalling and installing the same like on my PC. Any idea what I could be doing wrong?

**Comment by bdew** [comment]
> Caused by: java.lang.NoClassDefFoundError: scala/collection/Seq

Your installation is borked. This class is in a file that should have been installed with forge.

By default it should have been installed in \<minecraft>\\libraries\\org\\scala-lang\\scala-library\\2.11.1\\scala-library-2.11.1.jar 

Are you using the forge installer or some other launcher?

**Comment by OscarAblinger** [comment]
I'm using the curse launcher
I will check my installation once I'm at my laptop again and start a ticket on curse.

Thank you for your help

**Comment by bdew** [comment]
Hm i guess it's some bug in curse then. If that helps, with curse launcher the file should be in

\<curse folder>\\Install\\libraries\\org\\scala-lang\\scala-library\\2.11.1\\scala-library-2.11.1.jar

**Comment by OscarAblinger** [comment]
Just a quick update for anybody reading this/ to confirm it actually is a damaged installation:
The folder and the .jar existed in the installation.
Downloading the forge installer and installing the recommended version onto the curse installation of minecraft, fixed the problem.
