### ISSUE TITLE
[1.11.2] Misc.scala ModDetect functions not detecting Mods for Advanced Generators

### ISSUE THREAD

**Issue by spiffyriceburner** [bdew-minecraft/bdlib#39]
ic2 version: 2.7.72
[13:32:18] [Server thread/INFO] [advgenerators/advgenerators]: IC2 Version: NOT FOUND

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
