### ISSUE TITLE
SidedInvWrapper used when facing parameter is null 

### ISSUE THREAD

**Issue by SquidDev** [bdew-minecraft/bdlib#49]
See ForestryMC/ForestryMC#1542 for a similar instance of this.

`InventoryTile` constructs a `SidedInvWrapper` when requesting an `IItemHandler` instance. However, when the facing argument is null, a `SidedInvWrapper` is still constructed, which can cause issues when trying to use it - instead an `InvWraper` should be returned.

https://github.com/bdew/bdlib/blob/c37db5723a8b2ec324a8fefc4781ae0f1def23b5/src/net/bdew/lib/tile/inventory/BaseInventory.scala#L80

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
