### ISSUE TITLE
Crash when clicking with an empty bucket on the fluid gauge in pressure tanks' UI

### ISSUE THREAD

**Issue by MatthiasMann** [bdew-minecraft/bdlib#50]
Versions:
bdlib-1.14.3.12-mc1.12.2.jar
pressure-1.3.1.9-mc1.12.2.jar

I tried to extract fluid from a tank (containing 6000 mB of IC2 coolant) using a bucket but the slot which accept the bucket via shift click did not extract fluid so I took a bucket and click on various things on the UI.

[crash-2019-04-09_03.04.34-client.txt](https://github.com/bdew/bdlib/files/3056769/crash-2019-04-09_03.04.34-client.txt)

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
