### ISSUE TITLE
OutOfMemory Error

### ISSUE THREAD

**Issue by CepheidVariable** [bdew-minecraft/bdlib#55]
Trying to join a single player world throws java.lang.OutOfMemoryError: Metaspace

Removing BDLib and the dependency resolves.

[crash-2021-12-12_19.22.39-server.txt](https://github.com/bdew-minecraft/bdlib/files/7700329/crash-2021-12-12_19.22.39-server.txt)

**Comment by bdew** [comment]
This error means JVM has ran out of RAM allowed for class metadata.
Normally there should be no limit on that, unless you (or your launcher) passes a `-XX:MaxMetaspaceSize` argument when running java.
So either increase or remove the limit there.
