### ISSUE TITLE
Project icon for bdlib on curseforge?

### ISSUE THREAD

**Issue by Macleykun** [bdew-minecraft/bdlib#58]
Was wondering if ya have any idea/want a picture on your project bdlib on curseforge. That's all :-)

**Comment by bdew** [comment]
I don't think it really needs an icon considering it's just a library mod for use by my other mods... but if you feel like contributing something i can add it.

**Comment by Macleykun** [comment]
What idea's you have for the logo?

**Comment by Macleykun** [comment]
bump~

**Comment by Macleykun** [comment]
heya @bdew 
i have someone/a team of people that can draw an icon for your bdlib project.
You have any idea's/suggestions what you would maybe have?

**Comment by bdew** [comment]
I don't have any ideas and i personally don't see the need for an icon for a library mod that no one will be looking for / installing manually. It doesn't do anything interesting to the end user that could be represented as an icon.
