### ISSUE TITLE
РУКИ ИЗ ЖОПЫ БЛЯТЬ!

### ISSUE THREAD

**Issue by LaDerek** [bdew-minecraft/bdlib#59]

**Comment by daniorio** [comment]
Полностью согласен

**Comment by Will0376** [comment]
+1, bro

**Comment by Gunirs** [comment]
Не поспоришь

**Comment by mts2200** [comment]
Рил

**Comment by Serega007RU** [comment]
По факту

**Comment by bdew** [comment]
wat.

**Comment by mts2200** [comment]
Version 1.7.10 has a bug that allows you to access the database. Because of this, one of the major Russian projects was hacked yesterday. Now in this way you can hack any server where this problem is not fixed and there is AE2Stuff + BDLIB.

**Comment by bdew** [comment]
1.7.10 version is ~7 years old. I'm sorry that your server got hacked but I don't have the time or energy to release updates for every old version of Minecraft.

Also it would be nice to provide actual details instead of spamming rude russian messages.
