### ISSUE TITLE
BdLib has failed to load correctly

### ISSUE THREAD

**Issue by MKr4zy** [bdew-minecraft/bdlib#60]
I'm running into Problems when trying to load the game with any version of BdLib on 1.19.
Forge is version 41.1.0

The Error message I'm getting is "java.lang.NoSuchMethodException: net bdew.lib.BdLib.<init>()"

I've attached the crash report.
[crash-2022-09-08_15.00.39-fml.txt](https://github.com/bdew-minecraft/bdlib/files/9526984/crash-2022-09-08_15.00.39-fml.txt)

**Comment by bdew** [comment]
Update Scalable Cat's Force - build 6 had a bug with loading mods, it's fixed in 7+
