### ISSUE TITLE
Major debug log spam

### ISSUE THREAD

**Issue by K-4U** [bdew-minecraft/bdlib#8]
Hello,

I've noticed that bdlib prints a lot of stuff to the console when starting. And i mean, a LOT!
Honestly, most of it isn't really needed. I'm trying to get mod authors to make a config option in their mod, to allow for the entire turning off of logging.

Modpacks can load a lot faster this way, because printing to the console takes time.
If you want i can look into your code and create a PR for it, but i cannot decide for you what fits in what category and what not.

With kind regards,
~K4Unl

**Comment by bdew** [comment]
Do you have any actual data about logging slowing down startup?

I did some casual poking around with visualvm and from a 25 second startup (with just my mods + forestry) less than 500ms was spent in logging, which is pretty negligible. 

The vast majority of startup time seems to be spent in loading and processing bytecode and other IO (loading and decompressing textures, etc.), the second biggest offender in my mods is most probably the parser for BACON.

I don't like the idea of a config option, even right now getting useful reports from users is a pain in the arse. Having them change an option, reproduce the bug and then upload the log would probably be an exercise in futility.
