### ISSUE TITLE
Question:  Guidance on using bdlib in another mod.

### ISSUE THREAD

**Issue by dakamojo** [bdew-minecraft/bdlib#9]
Can you please provide some guidance on using bdlib in the development of another mod?  I understand the project structure of a minecraft mod, but not how to utilize and API such as this, where I want to link to classes but not distribute the binary.

Do I need a deobf version of the jar file?

**Comment by bdew** [comment]
You will need to add something like this to your build.gradle:

```
repositories {
    maven {
        name = "bdew"
        url = "http://jenkins.bdew.net/maven"
    }
}
dependencies {
    compile "net.bdew:bdlib:1.6.2.41"
}
```

Then refresh the project in your IDE and that's pretty much it.

**Comment by dakamojo** [comment]
Thanks.  I understand that part now, but I don't understand how I configure my project to know the classes available in the library.  I'm using eclipse.  Do I need to add a reference to an external jar?  And if so, where is the jar actually located?  Is it cached someplace?

**Comment by bdew** [comment]
Not sure about eclipse as i use Intellij IDEA, but i think the classes should be available for use automatically after you add the library to gradle and refresh the project.
